spring:
  profiles:
    active: prod
    default: prod
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:db/data.sql

  config:
    import:
      - external-api-config.yml
      - pageable-config.yml
      - private/application-private.yml

logging:
  level:
    sql: trace
